#index:
#    path: /
#    controller: App\Controller\DefaultController::index

filmes:
  type: rest
  resource: App\Controller\FilmesController

filmes_post:
  path: /filmes
  methods: [POST]
  defaults:
    _controller: App\Controller\FilmesController:postFilmesAction
    _format: json

filmes_patch:
  path: /filmes/{filme}
  methods: [PATCH]
  defaults:
    _controller: App\Controller\FilmesController:patchFilmeAction
    _format: json

pessoas:
  type: rest
  resource: App\Controller\PessoasController

pessoas_post:
  path: /pessoas
  methods: [POST]
  defaults:
    _controller: App\Controller\PessoasController:postPessoasAction
    _format: json

filmes_papeis_post:
  path: /filmes/{filme}/papeis
  methods: [POST]
  defaults:
    _controller: App\Controller\FilmesController:postPapeisFilmeAction
    _format: json