#index:
#    path: /
#    controller: App\Controller\DefaultController::index

filmes:
  type: rest
  resource: App\Controller\FilmesController

filmes_post:
  path: /filmes
  methods: [POST]
  defaults:
    _controller: App\Controller\FilmesController:postFilmesAction
    _format: json